version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
